version: "2"
services:
  plex:
    container_name: plex
    image: plexinc/pms-docker
    restart: unless-stopped
    ports:
      - 32400:32400/tcp
      - 8324:8324/tcp
      - 32469:32469/tcp
      - 1900:1900/udp
      - 32410:32410/udp
      - 32412:32412/udp
      - 32413:32413/udp
      - 32414:32414/udp
    environment:
      - TZ=Etc/UTC
      - PLEX_CLAIM= #optional
      - ADVERTISE_IP=http://localhost:32400/
    hostname: localhost
    volumes:
      # - <path/to/plex/database>:/config
      # - <path/to/transcode/temp>:/transcode
      # - <path/to/media>:/data
      # - /path/to/library:/config
      - /mnt/e/peliculas:/movies
      - /mnt/e/series:/tv
      - /mnt/e/otros:/otros
