version: '2'
services:
  homebridge:
    image: homebridge/homebridge:latest
    restart: always
    # network_mode: host # con host no funiciona
    ports:
      - 8581:8581
    volumes:
      - /SETUP/homebridge:/homebridge
    logging:
      driver: json-file
      options:
        max-size: "10mb"
        max-file: "1"
