version: "3"
services:
  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
      # - /PATH_TO_YOUR_CONFIG:/config
      - /SETUP/home-assistant/config:/config
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    privileged: true
    # network_mode: host # con host no funciona usar ports
    ports:
      - 8123:8123
  homebridge:
    container_name: homebridge
    image: homebridge/homebridge:latest
    restart: always
    # network_mode: host # con host no funiciona
    ports:
      - 8581:8581
    volumes:
      - /SETUP/homebridge:/homebridge
    logging:
      driver: json-file
      options:
        max-size: "10mb"
        max-file: "1"
